### PR TITLE
feat!: add `defineConfigObject` and ref writeback

### PR DESCRIPTION
**Pull request by antfu**
This would allow this lib to work with `vscode-ext-gen` like:

```ts
import { defineConfigsWithDefaults, reactive, ref } from 'reactive-vscode'
import { scopedConfigs, ScopedConfigKeyTypeMap } from './generated-meta'

export const config = reactive(
  defineConfigsWithDefaults<ScopedConfigKeyTypeMap>(
    scopedConfigs.scope,
    scopedConfigs.defaults,
  )
)
```

Supporting write-back for ref makes it more like a ref; otherwise, we could have a `readonly` version that would disallow that. But in general, when we want to wrap it with `reactive, ' I think being able to write back would make the DX better in those cases.

### CODE REVIEW

**Comment by KermanX** [comment]
I made some tests previously and found that if the default value is not provided in the `package.json`, VSCode will use its default value. For example, `""` for string, and `false` for boolean. It seems that `WorkspaceConfiguration.get` returns `undefined` only when the configuration is not defined. So I am not sure what's the use case of `scopedConfigs.defaults`.

**Comment by antfu** [comment]
- `scopedConfigs.defaults` provides the keys for us to know what configs are available.
- Providing the value is more like defensive programming, where we depend less on VS Code's behavior. In the end, it doesn't matter, use `WorkspaceConfiguration.get` would work as well. On `vscode-ext-gen` we will still generate those values in case users want to consume it programmatically.

**Comment by KermanX** [comment]
> * Providing the value is more like defensive programming, where we depend less on VS Code's behavior. In the end, it doesn't matter, use `WorkspaceConfiguration.get` would work as well. On `vscode-ext-gen` we will still generate those values in case users want to consume it programmatically.

I agree that the default value can be generated, but I think we should always use the value from `WorkspaceConfiguration.get` as the initial value.

In the last commit, I made a change to restore the old usage of `ConfigRef`, while adding a `ConfigObject` which has a `$update` method. This is because I think `WorkspaceConfiguration.update` is not a small operation - it may create `.vscode/settings.json` and should be used carefully. After all, a separate `update` method is a must because there are 2 additional params in `WorkspaceConfiguration.update`.

**Comment by antfu** [comment]
Yeah, that would also do. In that case, we should mark the ref and reactive as readonly to communicate this better.

> I think we should always use the value from WorkspaceConfiguration.get as the initial value.

Sure, no problem.

**Comment by KermanX** [comment]
> Yeah, that would also do. In that case, we should mark the ref and reactive as readonly to communicate this better.

When I read this, I suddenly realized that it is completely reasonable to write back when setting `.value`. I used to think that sometimes we need to update the ref without writing back - which now I think can be done in a more intuitive way - and we should let `ConfigRef` just always represent the current config value.

I also changed the signature so that both two ways to provide the types work now. There is a little overlapping between the two overrides, but since the runtime effect is exactly the same, I think this is not a big problem.

**Review by KermanX — APPROVED** [review]

**Pull request merged**
